INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (1,"Mr.Chocolate", 5,"M", "black", "calm", true)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (2, "Rowdy", 6, "M", "grey", "happy", false)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (3, "Tabitha", 7, "M", "white", "happy", true)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (4, "Sergeant Brown", 9, "F", "grey", "angry", true)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (5, "Mellisa", 10, "M", "black", "happy", true)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (6, "Grinch",4, "F", "grey", "calm", false)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (7,"Wendy", 7, "F", "black", "goofy", true)
INSERT INTO bears (id, name, age, sex, color, temperament, alive)  VALUES (8,NULL, 6, "F", "white", "calm", true)